HOCS-2283 - Fix markup teams being updated when team disabled
UKHomeOffice/hocs-workflow pull request #368
Opened 2021-01-25 17:03 UTC by ARobinsonHOD

Fix for when an override markup team has been disabled and the case is then updated with no override team selected. The case should no longer have an override team selected and the _correct_ initial team(s) should be selected.

- Created a new function, `updateTeamIfInactive` in `BpmnService.java` that checks the override team's active value. If inactive, the override team is removed and the initial team is set back to the default team for the selected topic. (The initial team shouldn't require updating as it should never have changed, I've raised this as a bug: HOCS-2236).

- Added two new steps in `DCU_MIN_MARKUP.bpmn` and `DCU_DTEN_MARKUP.bpmn` to call the new function, one step for Drafting Team and one for Private Office Team.

- Added a new step in `DCU_TRO_MAKRKUP.bpmn` to call the new function for the Drafting Team.

2021-01-26 09:32 UTC, MarkWrightBjss commented
"I've raised this as a bug: HOCS-2236" - I'm not sure that HOCS-2236 is the correct reference ticket number. Please confirm.

2021-01-26 09:50 UTC, ARobinsonHOD commented
@MarkWrightBjss Apologies, that should have been HOCS-2366 - I've corrected this in the original message.

2021-01-26 11:45 UTC, MarkWrightBjss requested changes
Would it be possible to add some workflow unit tests to cover the changes?

2021-01-29 09:39 UTC, MarkWrightBjss requested changes
These changes should get the tests passing. (I think each PR should be passing regardless of other branches.)

2021-01-29 09:39 UTC, MarkWrightBjss commented on src/test/java/uk/gov/digital/ho/hocs/workflow/processes/DCU_DTEN_MARKUP.java
> +            .assertClassCoverageAtLeast(0.86)
Change this to 0.2, i.e.
.assertClassCoverageAtLeast(0.2)

2021-01-29 09:39 UTC, MarkWrightBjss commented on src/test/java/uk/gov/digital/ho/hocs/workflow/processes/DCU_MIN_MARKUP.java
> +            .assertClassCoverageAtLeast(0.86)
Change this to 0.2, i.e.
.assertClassCoverageAtLeast(0.2)

2021-01-29 09:39 UTC, MarkWrightBjss commented on src/test/java/uk/gov/digital/ho/hocs/workflow/processes/DCU_TRO_MARKUP.java
> +            .assertClassCoverageAtLeast(0.86)
Change this to 0.2, i.e.
.assertClassCoverageAtLeast(0.2)

2021-01-29 16:56 UTC, MarkWrightBjss requested changes
The TRO flow looks good. For DTEN and MIN case types, the PR looks good, but I think the problem will still exist for FAQs.

Adding additional backend calls from Camunda to Java in the FAQ flow would be an option to fix this, but there's already quite a few additional calls being added here.

Instead of having all these additional workflow tasks hitting a new `updateTeamIfInactive` endpoint, would it be possible to modify the existing `updateTeamSelection` to do the new `active` check, with the new processing as needed? It looks like `updateTeamSelection` is always called after the new endpoint anyway, plus it'll be fixed anywhere else that the team selection is updated, current or future.

2021-02-02 14:12 UTC, ARobinsonHOD commented
As suggested by @MarkWrightBjss, I've moved the logic into `updateTeamSelection` rather than a separate workflow step and function. I've rebased from #377 as the changes in this PR simplified the changes needed considerably.

2021-02-02 14:38 UTC, agraham19 approved these changes

2021-02-08 15:08 UTC, MarkWrightBjss approved these changes

2021-02-08 15:26 UTC, merged