Feature/hocs 3384 move topics to case create
UKHomeOffice/hocs-workflow pull request #475
Opened 2021-07-20 15:17 UTC by gary-newbolt

2021-07-22 15:09 UTC, LaurieBennett requested changes
Change variable name and this will pass

2021-07-22 15:58 UTC, gary-newbolt commented on src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowService.java
> +            Optional<StageDto> maybeActiveStage = caseworkClient.getActiveStage(caseUUID);
Okay... I wouldn't want to change it. With the type being an `Optional` type, potentially the value could be null. `Optional` is a special Java class that contains a field of the same type as the generic passed in and often used on things such as this where a http call is made with no guarantee that you will get a result. In the subsequent lines, the variable is checked for existence, and if it exists, a more explicit name is given to the extracted object. So I think the term `maybe...` in this instance is appropriate.

2021-07-22 16:02 UTC, gary-newbolt commented on src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/GetStageResponse.java
> +@ToString
This should be taken out though.

2021-07-26 09:51 UTC, LaurieBennett commented on src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/GetStageResponse.java
> +@ToString
Agreed

2021-07-26 09:51 UTC, LaurieBennett commented on src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowService.java
> +            Optional<StageDto> maybeActiveStage = caseworkClient.getActiveStage(caseUUID);
I figured it was showing some of the merged changes as well, that sounds reasonable, from first look it sounded a bit too much like a temporary variable name, but after further discussion I'm fine with this.

2021-07-26 09:51 UTC, LaurieBennett approved these changes
Approved, PASS

2021-07-26 13:03 UTC, gary-newbolt commented on src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/GetStageResponse.java
> +@ToString
Removed

2021-07-26 15:02 UTC, merged