HOCS-4221: Add ability to transfer BF cases to SMC
UKHomeOffice/hocs-workflow pull request #652
Opened 2022-03-09 09:09 UTC by JosephRogerson

2022-03-09 11:00 UTC, gary-newbolt requested changes
There's an errant gateway I think here...
![Screenshot 2022-03-09 at 10 56 41](https://user-images.githubusercontent.com/32836753/157428732-8f462d5a-d720-4e96-8e64-d60bb6c26062.png)

2022-03-09 12:22 UTC, JosephRogerson commented
> There's an errant gateway I think here... ![Screenshot 2022-03-09 at 10 56 41](https://user-images.githubusercontent.com/32836753/157428732-8f462d5a-d720-4e96-8e64-d60bb6c26062.png)

I've removed that gateway

2022-03-21 15:55 UTC, gary-newbolt commented
Changes look good, just need to confirm which documents to transfer for BF --> SMC (PSU team)

2022-03-22 09:10 UTC, gary-newbolt approved these changes

2022-03-22 10:57 UTC, merged